# Site
name: 'animint2-blog'
description: 'animint2-blog is a dedicated blog for tutorials, experience and information sharing for animint2 package.'
logo: 'assets/images/animing2-logo.png'
baseurl: '/animint2-blog'
email: 'email@example.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    lazycipher:
      name:           lazycipher
      site:           https://lazycipher.js.org
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Himanshu Singh(@lazycipher) maintainer of this blog dedicated to animint2!"
      twitter:        https://twitter.com/lazycipher

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: lazycipher
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
