# Site
name: 'animint2-blog'
description: 'animint2-blog is a dedicated blog for tutorials, experience and information sharing for animint2 package.'
logo: 'assets/images/animing2-logo.png'
baseurl: '/animint2-blog'
email: 'email@example.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    lazycipher:
      name:           lazycipher
      site:           https://lazycipher.js.org
      avatar:         /assets/images/lazycipher_prof_pic.jpg
      bio:            "Hi, I am Himanshu Singh(@lazycipher) maintainer of this blog dedicated to animint2! I'm workin on this project as a Google Summer of Code 2020 student under R Project for Statistical Computing."
      twitter:        https://twitter.com/lazycipher
      github:         https://github.com/lazycipher
    tdhock:
      name:           'tdhock'
      site:           http://tdhock.github.io/
      github:         https://github.com/tdhock
      avatar:         /assets/images/tdhock_prof_pic.jpg
      bio:            "Toby Dylan Hocking, PhD, Machine learning lab director School of Informatics, Computing, and Cyber Systems Northern Arizona University. He's Statistical machine learning researcher, focusing on fast optimization algorithms for big data."

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: lazycipher
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
